name: Github Actions Demo

on: 
  push: 
    branches:
      - main
    paths:
      - '!.github/**'
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      triggering_event_name: ${{ github.event_name }}
      branch: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - run: tree
    
